package disciplinepolicycmd

import (
	"github.com/spf13/cobra"

	"github.com/reponerve/reponerve/internal/agent/discipline"
	"github.com/reponerve/reponerve/internal/cli/devwire"
	"github.com/reponerve/reponerve/internal/config"
)

// NewCommand creates the discipline-policy subcommand.
func NewCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "discipline-policy",
		Short: "Show repo-adaptive Native Development Discipline policy",
		Long:  `Display .reponerve/discipline-policy.json generated by scan.`,
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			policy, err := discipline.LoadPolicy(config.GetWorkspaceDir())
			if err != nil {
				return err
			}
			return devwire.WriteDEResult(cmd, discipline.FormatPolicy(policy), policy)
		},
	}
	return devwire.BindDECmd(cmd)
}
